name: Compile Resume PDF

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  compile-resume:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up LaTeX with full TeX Live
      uses: xu-cheng/setup-latex@v1
      with:
        version: 'latest'
        
    - name: Install additional fonts
      run: |
        sudo apt-get update
        sudo apt-get install -y fonts-liberation fonts-liberation-sans fonts-liberation-serif
        sudo fc-cache -fv
        
    - name: Compile with XeLaTeX
      run: |
        xelatex -interaction=nonstopmode -output-directory=. fixed.tex
        xelatex -interaction=nonstopmode -output-directory=. fixed.tex
        
    - name: Check if PDF was created
      run: |
        if [ -f "fixed.pdf" ]; then
          echo "PDF compilation successful"
          ls -la *.pdf
        else
          echo "PDF compilation failed"
          cat fixed.log
          exit 1
        fi
        
    - name: Commit PDF to repository
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add fixed.pdf
        git commit -m "Auto-compile: Update resume PDF [skip ci]" || exit 0
        git push 